Updated PR-check worklfow to debug env

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -20,10 +20,14 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with: 
-          node-version: '20.18.1'
+          node-version: '20.x'
       
       - name: Install Dependencies
         run: npm ci
+      
+      - name: Check if package exists locally
+        run: npm list jest || echo "jest package not found"
+        run: npm list fastify || echo "fastify package not found"
       
       - name: Run Tests
         run: npm test
